### ISSUE TITLE
減少開關門截圖等待時間

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-DoorMonitor#4]
直接把 Hydra DVR 固定對著門，不使用轉向，減少為了等待攝影機轉向造成的截圖時間差

**Comment by zxp86021** [comment]
沒有 DVR 了，先關

**Comment by bluet** [comment]
@zxp86021 ㄟㄟㄟ，DVR 應該還在呀

**Comment by zxp86021** [comment]
應該說是和融的 server 連不到，所以現在是取不到圖的狀態

**Comment by bluet** [comment]
目前連線是用哪個 ip/fqdn？

**Comment by zxp86021** [comment]
> 目前連線是用哪個 ip/fqdn？

`ncnu.hydra.click:65432`

**Comment by bluet** [comment]
啊.... 因為 hydra.click 我今年沒續約了....

**Comment by bluet** [comment]
我晚點來查一下 ip 是多少

**Comment by zxp86021** [comment]
可是它好像死很久了XD

**Comment by bluet** [comment]
剛剛看了一下，網域好像是四月到期的... 不過在更早之前我忘了有沒有把主機重開過 XDDD

**Comment by zxp86021** [comment]
之前學校某次停電過後就壞了
